# Generated by Django 3.2 on 2021-05-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='villageapp.panchayath')),
            ],
        ),
    ]
