# Generated by Django 3.2 on 2021-05-07 07:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0004_enduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default='false')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='villageapp.employees')),
                ('panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Leaveapplication', to='villageapp.panchayath')),
            ],
        ),
    ]
