# Generated by Django 3.2 on 2021-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0005_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
