# Generated by Django 3.2 on 2021-05-08 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0007_alter_leaveapplication_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employees', to='villageapp.employees'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='panchayath',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leaveapplication', to='villageapp.panchayath'),
        ),
    ]
