# Generated by Django 3.2 on 2021-05-08 06:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0008_auto_20210508_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=100)),
                ('solved', models.BooleanField(default='False')),
                ('enduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='villageapp.enduser')),
                ('panchayath', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Complaint', to='villageapp.panchayath')),
            ],
        ),
    ]
