# Generated by Django 3.2 on 2021-05-11 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('villageapp', '0010_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('da', models.IntegerField()),
                ('credited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='villageapp.employees')),
                ('panchayath', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='villageapp.panchayath')),
            ],
        ),
    ]
